package com.myspace.customrulepermitportal;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ObjectToValidate implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "value1_string")
	private java.lang.String value1_string;
	@org.kie.api.definition.type.Label(value = "value2_int")
	private java.lang.Integer value2_int;
	@org.kie.api.definition.type.Label(value = "value3_bool")
	private java.lang.Boolean value3_bool;

	public ObjectToValidate() {
	}

	public java.lang.String getValue1_string() {
		return this.value1_string;
	}

	public void setValue1_string(java.lang.String value1_string) {
		this.value1_string = value1_string;
	}

	public java.lang.Integer getValue2_int() {
		return this.value2_int;
	}

	public void setValue2_int(java.lang.Integer value2_int) {
		this.value2_int = value2_int;
	}

	public java.lang.Boolean getValue3_bool() {
		return this.value3_bool;
	}

	public void setValue3_bool(java.lang.Boolean value3_bool) {
		this.value3_bool = value3_bool;
	}

	public ObjectToValidate(java.lang.String value1_string,
			java.lang.Integer value2_int, java.lang.Boolean value3_bool) {
		this.value1_string = value1_string;
		this.value2_int = value2_int;
		this.value3_bool = value3_bool;
	}

}